### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by zengbowenbit** [regisin/ns-3-obstacles#1]
When I build the ns-3-obstacles, an error happens. It shows that **_‘class ns3::GaussMarkovMobilityModel’ has no member named ‘AddObstacle’_**. I'm not sure if there are some bugs in the mobility model. Could you offer some help?
![image](https://user-images.githubusercontent.com/31918620/44501551-4b2d6d00-a6c0-11e8-84f8-5ea0531e934e.png)

**Comment by zengbowenbit** [comment]
Anyway, I bulit it successfully when I removed the file NetGauss.cc. However, I can't figure out the bug since 'AddObstacle' works well in other codes and only gets wrong here.

**Comment by regisin** [comment]
The NetGauss.cc has the wrong model configured:

Instead of `GaussMarkovMobilityModel`, use `ObstacleGaussMarkovMobilityModel` when creating the object, let me know if it works then.

I updated my PC, so that version of ns-3 does not compile correctly here. However, if I fix that, that error disappears, though others prevent compiling.

**Comment by zengbowenbit** [comment]
> The NetGauss.cc has the wrong model configured:
> 
> Instead of `GaussMarkovMobilityModel`, use `ObstacleGaussMarkovMobilityModel` when creating the object, let me know if it works then.
> 
> I updated my PC, so that version of ns-3 does not compile correctly here. However, if I fix that, that error disappears, though others prevent compiling.

That's it! It works when I replace the **_GaussMarkovMobilityModel_** with **_ObstacleGaussMarkovMobilityModel_** as you said.

**Comment by zengbowenbit** [comment]
Can you tell me which ns-3 version are your codes? Because I am trying to modify the codes to test the **_average end-to-end delay_** between nodes.

And can you give me some hints about how to do that?

**Comment by regisin** [comment]
This model was developed on top of the ns-3.23. As far as I know, there is no mobility module maintainer, so porting to a newer version (3.29 was recently released) might be easy.

Edit:
Is the test you are trying to run a mobility model test script? If it is one of the ns-3 tests (not made by me), I suggest you contact the `ns-3-users` google group for help.
